version: "3.5"
services:
  admin_app_gateway:
    env_file:
      - .env
    build: .
    image: main_image:latest
    command: bash -c "python3 manage.py runserver 0.0.0.0:5700"
    ports:
      - "5700:5700"
    deploy:
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        delay: 3s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - .:/src
      - /opt/logs:/opt/logs
    networks:
      - main_network
networks:
  main_network:
    external: true
extra_hosts:
  - "host.docker.internal:host-gateway"